title: İsmail Öcal
description: İsmail Öcal'ın Kişisel Blogu

url: http://ismailocal.github.io
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Ana Sayfa
   url: /
 - title: Hakkımda
   url: /about

social:
   github: ismailocal
   twitter: false
   facebook: ismailocal
   email: ismailocal@gmail.com

google_analytics: false
