title: İsmail Öcal
description: İsmail Öcal'ın Kişisel Blogu
keywords: "İsmail Öcal, Kişisel Blog, Blog"

url: http://ismailocal.com
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /
 - title: About
   url: /about

social:
   github: ismailocal
   twitter: false
   facebook: ismailocal
   email: ismailocal@gmail.com

google_analytics: "UA-62889313-1"
