# Site settings
title: İsmail Öcal
email: ismailocal@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  İsmail Öcal'ın Kişisel Blogu
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ismailocal.github.io" # the base hostname & protocol for your site
twitter_username: null
github_username:  ismailocal

# Build settings
markdown:    redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]