title: İSMAİL ÖCAL
description: İsmail Öcal'ın Kişisel Blogu

url: http://ismailocal.github.io
baseurl: ""
paginate_path: "/page:num/"
permalink: /:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Home
   url: /index.html

social:
   github: ismailocal
   twitter: false
   facebook: ismailocal
   email: ismailocal@gmail.com

google_analytics: false
